# Generated by Django 5.2.3 on 2025-07-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseekerprofile')),
            ],
        ),
    ]
