# Generated by Django 5.2.3 on 2025-07-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpage',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
