# Generated by Django 5.2.3 on 2025-07-01 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('required_experience', models.CharField(max_length=100)),
                ('required_education', models.CharField(max_length=100)),
                ('required_skills', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('application_method', models.CharField(max_length=100)),
                ('application_deadline', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
