# Generated by Django 5.2.3 on 2025-06-30 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('company_location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('company_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
